### ISSUE TITLE
2.11+ represents service names in the UI and dependency graph differently than before

### ISSUE THREAD

**Issue by AceHack** [openzipkin/zipkin#2342]
The 2.10 docker image works fine, 2..11 or newer breaks nesting and also the service graph.

I'm running the following
2.10 - `docker run --rm -it -p 9411:9411 openzipkin/zipkin:2.10`
2.11 - `docker run --rm -it -p 9411:9411 openzipkin/zipkin:2.11`

2.10 - Working
![2 10](https://user-images.githubusercontent.com/578953/50666042-088a7400-0f81-11e9-83ef-ee838219a24d.jpg)

2.11 - Broken Nesting
![2 11](https://user-images.githubusercontent.com/578953/50666045-0a543780-0f81-11e9-9e41-7c25a124ac2f.jpg)

The following code is using .NET core 2.1
```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using zipkin4net;
using zipkin4net.Middleware;
using zipkin4net.Tracers.Zipkin;
using zipkin4net.Transport.Http;

namespace TracingTest
{
    class Program
    {
        static readonly DateTime _startDateTime;
        static readonly long _startTicks;
        static Program()
        {
            _startDateTime = DateTime.UtcNow;
            _startTicks = System.Diagnostics.Stopwatch.GetTimestamp();
        }

        static async Task Main(string[] args)
        {
            using (var services = new ServiceCollection()
                .AddLogging(builder =>
                {
                    builder
                    .AddConsole()
                    .AddDebug();
                })
                .BuildServiceProvider()
            )
            {
                TraceManager.SamplingRate = 1;
                var loggerFactory = services.GetRequiredService<ILoggerFactory>();
                var logger = new TracingLogger(loggerFactory, "Tracing");
                var sender = new HttpZipkinSender("http://localhost:9411", "application/json");
                var serializer = new JSONSpanSerializer();
                var tracer = new ZipkinTracer(sender, serializer);
                TraceManager.RegisterTracer(tracer);
                TraceManager.Start(logger);

                // Timings
                var uiStart = UtcNow;
                var gatewayStart = uiStart.AddMilliseconds(10);
                var gatewayCallAuthStart = gatewayStart.AddMilliseconds(10);
                var gatewayCallProfileStart = gatewayStart.AddMilliseconds(20);
                var authStart = gatewayCallAuthStart.AddMilliseconds(10);
                var authEnd = authStart.AddMilliseconds(500);
                var gatewayCallAuthEnd = authEnd.AddMilliseconds(10);
                var profileStart = gatewayCallProfileStart.AddMilliseconds(10);
                var profileEnd = profileStart.AddMilliseconds(100);
                var gatewayCallProfileEnd = profileEnd.AddMilliseconds(10);
                var gatewayEnd = new DateTime(Math.Max(gatewayCallAuthEnd.Ticks, gatewayCallProfileEnd.Ticks), DateTimeKind.Utc).AddMilliseconds(10);
                var uiEnd = gatewayEnd.AddMilliseconds(10);

                // UI Call Gateway
                var uiTrace = Trace.Create();
                uiTrace.Record(Annotations.ServiceName("client"));
                uiTrace.Record(Annotations.Rpc("get-user"));
                uiTrace.Record(Annotations.ClientSend(), uiStart);
                uiTrace.Record(Annotations.ClientRecv(), uiEnd);

                // Gateway
                var gatewayTrace = uiTrace.Child();
                gatewayTrace.Record(Annotations.ServiceName("api-gateway"));
                gatewayTrace.Record(Annotations.Rpc("get-user"));
                gatewayTrace.Record(Annotations.ServerRecv(), gatewayStart);
                gatewayTrace.Record(Annotations.ServerSend(), gatewayEnd);

                // Gateway Call Auth
                var gatewayCallAuthTrace = gatewayTrace.Child();
                gatewayCallAuthTrace.Record(Annotations.ServiceName("auth-service"));
                gatewayCallAuthTrace.Record(Annotations.Rpc("get-permissions"));
                gatewayCallAuthTrace.Record(Annotations.ClientSend(), gatewayCallAuthStart);
                gatewayCallAuthTrace.Record(Annotations.ClientRecv(), gatewayCallAuthEnd);

                // Gateway Call Profile
                var gatewayCallProfileTrace = gatewayTrace.Child();
                gatewayCallProfileTrace.Record(Annotations.ServiceName("api-gateway"));
                gatewayCallProfileTrace.Record(Annotations.Rpc("get-profile"));
                gatewayCallProfileTrace.Record(Annotations.ClientSend(), gatewayCallProfileStart);
                gatewayCallProfileTrace.Record(Annotations.ClientRecv(), gatewayCallProfileEnd);

                // Auth Service
                var authTrace = gatewayCallAuthTrace.Child();
                authTrace.Record(Annotations.ServiceName("auth-service"));
                authTrace.Record(Annotations.Rpc("get-permissions"));
                authTrace.Record(Annotations.ServerRecv(), authStart);
                authTrace.Record(Annotations.ServerSend(), authEnd);

                // Profile Service
                var profileTrace = gatewayCallProfileTrace.Child();
                profileTrace.Record(Annotations.ServiceName("profile-service"));
                profileTrace.Record(Annotations.Rpc("get-profile"));
                profileTrace.Record(Annotations.ServerRecv(), profileStart);
                profileTrace.Record(Annotations.ServerSend(), profileEnd);


                // Wait for key to close program
                Console.ReadKey(true);
                TraceManager.Stop();
                TraceManager.ClearTracers();
            }
        }

        static DateTime UtcNow => _startDateTime.AddTicks(System.Diagnostics.Stopwatch.GetTimestamp() - _startTicks);
    }
}
```

See issue on client for more info
https://github.com/openzipkin/zipkin4net/issues/224

**Comment by codefromthecrypt** [comment]
thanks. can you click json button for this trace and post it here?

**Comment by shakuzen** [comment]
Could you also make sure it is pulling the latest `2.11` tag? Or tell us which version of the server this is happening on by the response from `GET /info`?

**Comment by ericrini** [comment]
@shakuzen I can reproduce this using the latest Java servers from https://search.maven.org/artifact/io.zipkin.java/zipkin-server/2.11.12/jar without Docker.

**Working**
1.31.3 (previous major)
2.10.4 (previous minor)

**Not Working**
2.11.11 (previous patch)
2.11.12 (current release)

@adriancole I am working with @AceHack, here is some example JSON that will produce the issue he is describing.

```json
[
  {
    "traceId": "82f19ddbf1c198d5",
    "parentId": "9b2abf05c6a28bb2",
    "id": "2ba9698b4f57e0e0",
    "kind": "SERVER",
    "name": "get-profile",
    "timestamp": 1546867265116240,
    "duration": 71584,
    "localEndpoint": {
      "serviceName": "profile-service",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  },
  {
    "traceId": "82f19ddbf1c198d5",
    "parentId": "ec81655e993ee849",
    "id": "9b2abf05c6a28bb2",
    "kind": "CLIENT",
    "name": "get-profile",
    "timestamp": 1546867265100625,
    "duration": 102427,
    "localEndpoint": {
      "serviceName": "user-gateway",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "82f19ddbf1c198d5",
    "parentId": "ec81655e993ee849",
    "id": "e46180afb80e0446",
    "kind": "CLIENT",
    "name": "get-permissions",
    "timestamp": 1546867265100882,
    "duration": 209254,
    "localEndpoint": {
      "serviceName": "user-gateway",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "82f19ddbf1c198d5",
    "parentId": "127bea9a4ee1ba8d",
    "id": "ec81655e993ee849",
    "kind": "SERVER",
    "name": "get-user",
    "timestamp": 1546867265092201,
    "duration": 240912,
    "localEndpoint": {
      "serviceName": "user-gateway",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  },
  {
    "traceId": "82f19ddbf1c198d5",
    "id": "127bea9a4ee1ba8d",
    "kind": "CLIENT",
    "name": "get-user",
    "timestamp": 1546867265080236,
    "duration": 263885,
    "localEndpoint": {
      "serviceName": "client",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "82f19ddbf1c198d5",
    "parentId": "e46180afb80e0446",
    "id": "8d8f18293582266d",
    "kind": "SERVER",
    "name": "get-permissions",
    "timestamp": 1546867265112346,
    "duration": 183696,
    "localEndpoint": {
      "serviceName": "auth-service",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  }
]
```

**Comment by codefromthecrypt** [comment]
thanks for all the details

**Comment by codefromthecrypt** [comment]
it looks like there is a data problem we didn't account for in the latest server code.

the shared flag means the server has the same span id as the client. here you can see the shared flag is incorrectly set as the client and server do not share a span id.

the library should be fixed to not set shared flag when not sharing an ID parsed from headers.

meanwhile can you test against latest snapshot in case we already accounted for this data problem server side since last release?

https://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/java/zipkin-server/2.11.2-SNAPSHOT/zipkin-server-2.11.2-20180819.050659-6-exec.jar

**Comment by codefromthecrypt** [comment]
oops this is actually the correct latest snapshot
link zipkin-server-2.11.13-20190107.062025-14-exec.jar

**Comment by AceHack** [comment]
So I just ran the jar file from https://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/java/zipkin-server/2.11.13-SNAPSHOT/zipkin-server-2.11.13-20190107.062025-14-exec.jar

And it did not fix the issue.

![image](https://user-images.githubusercontent.com/578953/50838915-2f53fc00-132d-11e9-91ec-3ec15ea2fdde.png)

```
[
  {
    "traceId": "53df269d1222145a",
    "parentId": "f39c2f9f496ec3f8",
    "id": "737482d98c973e19",
    "kind": "SERVER",
    "name": "get-profile",
    "timestamp": 1546959945748631,
    "duration": 100000,
    "localEndpoint": {
      "serviceName": "profile-service",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  },
  {
    "traceId": "53df269d1222145a",
    "parentId": "a052e711897376d5",
    "id": "19fad211d53cf956",
    "kind": "CLIENT",
    "name": "get-permissions",
    "timestamp": 1546959945698631,
    "duration": 520000,
    "localEndpoint": {
      "serviceName": "auth-service",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "53df269d1222145a",
    "parentId": "a052e711897376d5",
    "id": "f39c2f9f496ec3f8",
    "kind": "CLIENT",
    "name": "get-profile",
    "timestamp": 1546959945738631,
    "duration": 120000,
    "localEndpoint": {
      "serviceName": "api-gateway",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "53df269d1222145a",
    "id": "46c96eaf94956f5f",
    "kind": "CLIENT",
    "name": "get-user",
    "timestamp": 1546959945678631,
    "duration": 560000,
    "localEndpoint": {
      "serviceName": "client",
      "ipv4": "10.0.75.1"
    }
  },
  {
    "traceId": "53df269d1222145a",
    "parentId": "19fad211d53cf956",
    "id": "e5064baf50225be7",
    "kind": "SERVER",
    "name": "get-permissions",
    "timestamp": 1546959945708631,
    "duration": 500000,
    "localEndpoint": {
      "serviceName": "auth-service",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  },
  {
    "traceId": "53df269d1222145a",
    "parentId": "46c96eaf94956f5f",
    "id": "a052e711897376d5",
    "kind": "SERVER",
    "name": "get-user",
    "timestamp": 1546959945688631,
    "duration": 540000,
    "localEndpoint": {
      "serviceName": "api-gateway",
      "ipv4": "10.0.75.1"
    },
    "shared": true
  }
]
```

**Comment by AceHack** [comment]
Any update?

**Comment by codefromthecrypt** [comment]
we had a number of onsite workshops in january which was both good and bad (bad as many occupied and distracted by travel) https://cwiki.apache.org/confluence/display/ZIPKIN/Workshops

on this now, tho! thanks for the ping

**Comment by codefromthecrypt** [comment]
root (client) span 6f5f on service "client" lands on "api-gateway" as server span 76d5
    client span c3f8 lands on "profile-service" as server span 3e19
    client span f956 lands on "auth-service" as server span 5be7

The configuration bug is that client span f956 ("get-permissions") has the wrong local endpoint. It has accidentally put the remote service name as the local service name.

It should be the same as the server it was invoked on, not the server it is invoking. I suspect if you correct the config for "get-permissions" to set the correct local endpoint, to "api-gateway", not "auth-service" which is the remote service name, it will be fine.

I checked this and it presents properly when the data is correct.

**Comment by AceHack** [comment]
Why does this work fine in 2.10?

**Comment by AceHack** [comment]
also the .net client is automatically setting endpoints so this is a bug in the .net client?

**Comment by codefromthecrypt** [comment]
sorry this is won't fix. the instrumentation is sending incorrect data
which is better fixed where the problem exists. The fact that 2.10
accidentally worked is of no consequence here.

**Comment by AceHack** [comment]
@adriancole 2.10 and every single version before 2.10 work, not just 2.10, 2.11 broke this.  Even 1.x versions worked.

**Comment by codefromthecrypt** [comment]
the data is and was incorrect. what was always broke was the data. please
stop arguing as I have already taken time to debug this for you gratis

**Comment by AceHack** [comment]
@adriancole as you said before "it looks like there is a data problem we didn't account for in the latest server code."  So the server code changed to make it less robust to client/data issues.  This seems like a step backwards for the server code.  I don't disagree that the client should be fixed as well but since the server used to handle this scenario but now does not this seems like a step backwards.  From a .NET developers perspective it's sure making jaeger seem like it's worth exploring.

**Comment by codefromthecrypt** [comment]
do what you need to do. if jaeger can present incorrect data better and
that is a priority for you over fixing the problem.  probably you should do
that.
